### ISSUE TITLE
Tibetan translations of some labels

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-presentation#102]
it would be good to translate some of these into Tibetan:
- "missing page" (or just "missing" ?)
- "Xa" / "Xb" (where X can by any folio number, for instance "2a" / "2b")
- "image number X" (in English we have "img. X")
- "Xa / Xb missing"

@ngawangtrinley @jeehuajian ?

**Comment by jeehuajian** [comment]
"missing page" (or just "missing" ?) =  "ཆད།" 
"Xa" / "Xb" (where X can by any folio number, for instance "2a" / "2b") = "Xན་" / "Xབ་"
"image number X" (in English we have "img. X") = "པར་གྲངས་ 25"
"Xa / Xb missing" = "Xན་ / Xབ་ ཆད།"

**Comment by eroux** [comment]
excellent thanks! final question: how would you express an interval, for instance "Xa to Ya missing"? (for instance "12a to 15b missing")

**Comment by jeehuajian** [comment]
"Xa to Ya missing" = "Xན་ ནས་ Yན་ བར་ཆད།"
