### ISSUE TITLE
toggle full screen for embedded readers

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#54]
Replacing the 'Close mirador' button by 'Toggle full screen' will greatly improve the user experience of embedded readers [such as this one.](https://bdrc-reader.github.io/mugey-gonpa/tsannyid)

![image](https://user-images.githubusercontent.com/17675331/63071679-dd262980-bf52-11e9-92e7-8fa48c54db5c.png)

![image](https://user-images.githubusercontent.com/17675331/63071663-caabf000-bf52-11e9-87a5-3dfce88d2505.png)

**Comment by eroux** [comment]
I think ideally there would be two modes:
- mode 1:
   * the current one, replacing `Close Mirador` with `Close Viewer`
- mode 2:
   * `Full Screen` (both in full screen and not in full screen)

the mode could be passed as an option when instantiating Mirador... (the `scripts/embed-iframe.html` script would use different options than the main one. @berger-n does it seem reasonable to you?

**Comment by berger-n** [comment]
notice than you must add `allowfullscreen` parameter to `iframe` to make fullscreen work 
(see [updated docs](https://github.com/buda-base/public-digital-library/blob/master/BDRC_Embedded_Reader.md#using-an-iframe))
once it is done https://bdrc-reader.github.io/mugey-gonpa/tsannyid should be fully working

@eroux you mean a query parameter eg "menu=fullscreen"? 
(however I can't see a use case for the 'close viewer' button in the iframe... 
actually I thought I had it hidden already like in the `/view` route http://library.bdrc.io/view/bdr:W12827)

**Comment by eroux** [comment]
I'm on my phone and can't remember all the details of the mirador config... but I trust you to make the right decision, you know the situation and the use cases!

**Comment by eroux** [comment]
@ngawangtrinley I'm closing it, reopen if necessary
