### ISSUE TITLE
collection tree / index listing ratio adjustment

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#55]
The collection tree to index listing ratio currently gives more space to the item listing but collection trees require more space, both for bdrc.io and when embedded. 

A 50%/50% ratio as seen in this mirador demo doesn't seem unreasonable:
![image](https://user-images.githubusercontent.com/17675331/63073150-026a6600-bf5a-11e9-8a87-324445fb327e.png)

Our current 25%/75% ratio on bdrc.io...
![image](https://user-images.githubusercontent.com/17675331/63073091-b15a7200-bf59-11e9-9d6b-163331ba0617.png)

...and in an embedded reader
![image](https://user-images.githubusercontent.com/17675331/63072622-54f65300-bf57-11e9-9f1e-4e0669a39480.png)

**Comment by eroux** [comment]
seems reasonable to me, @berger-n what do you think?

**Comment by berger-n** [comment]
good idea! will do

**Comment by berger-n** [comment]
now the tree adjusts its size to its content
(minimum width is 25% - maximum is 50%)

**Comment by ngawangtrinley** [comment]
Thanks! Resizing does something a bit funny. have a look [here](https://bdrc-reader.github.io/mugey-gonpa/tsannyid)

![gif](https://user-images.githubusercontent.com/17675331/63211805-c89e8880-c12e-11e9-904e-9468d1a31d2a.gif)

Also I'd say we could go a bit further than 50% if the window adjusts to its content, 60%? 70%? It's already much better now. I'm just thinking that left side can have a lot of text, while the right side is just for thumbnails.

**Comment by berger-n** [comment]
everything should be fine now
(I've set max width to 75%)

**Comment by eroux** [comment]
@ngawangtrinley can we close this issue?

**Comment by ngawangtrinley** [comment]
There's still a small bug visible in embedded windows: when it's auto-adjusted with the titles the max goes to more than 80%, then jumps back and gets locked at 75% when re-adjusting manually. In small embedded windows this can make a difference. If it's complicated setting the max at 70% instead could do the trick.

I'm not sure if it's done on purpose but there doesn't seem to be auto/manual adjustment in full screen. Locking it at 50% mirador demo style might be nice.

**Comment by eroux** [comment]
is it ok now?
