### ISSUE TITLE
per-volume outline not showing up

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#56]
Here's a work that has an outline that shows in the catalog....
W25094
![image](https://user-images.githubusercontent.com/17675331/63491012-ae76f880-c4e8-11e9-830e-fa02d0ed327a.png)

... but doesn't show in the index panel:
![image](https://user-images.githubusercontent.com/17675331/63490944-85566800-c4e8-11e9-9a38-1befe727059c.png)

**Comment by eroux** [comment]
right, I'll handle that, it shouldn't be too complex

**Comment by eroux** [comment]
@ngawangtrinley it should be ok, can you confirm?
