### ISSUE TITLE
spurious empty footer

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#57]
shows in both embedded and fullscreen views
![image](https://user-images.githubusercontent.com/17675331/63491069-db2b1000-c4e8-11e9-807d-e79c44ca40ee.png)

**Comment by eroux** [comment]
@berger-n can you take a look?

**Comment by berger-n** [comment]
fixed as of commit https://github.com/buda-base/mirador/commit/1e4d9d66b618efba23f2b92b53cb4ea331a9a503
