### ISSUE TITLE
wrong image ratio when switching from page view to reading view

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#58]
![gif](https://user-images.githubusercontent.com/17675331/63491366-99e73000-c4e9-11e9-84ed-80254230e604.gif)

**Comment by eroux** [comment]
oh, that's weird, what's the url you're seing the bug at?

**Comment by ngawangtrinley** [comment]
same everywhere, on chrome, windows 10

**Comment by ngawangtrinley** [comment]
now a ratio issue:
![gif](https://user-images.githubusercontent.com/17675331/63524011-c755cd00-c52d-11e9-827b-17036c2acc77.gif)

**Comment by berger-n** [comment]
can't reproduce this bug
@ngawangtrinley can you? 
if so in which Collection/Volume?

**Comment by ngawangtrinley** [comment]
This should make it clearer:
![gif](https://user-images.githubusercontent.com/17675331/74208292-dbe57780-4cbd-11ea-9e27-425b6ad61638.gif)

**Comment by ngawangtrinley** [comment]
I didn't manage to reproduce the ratio one. I'll let you know if I find it again.

**Comment by berger-n** [comment]
thanks @ngawangtrinley!

**Comment by eroux** [comment]
@ngawangtrinley for mirador issues, please now use https://github.com/buda-base/mirador/issues/ (this one has been migrated there, closing it here)
