### ISSUE TITLE
bampos in the derge kangyur not accessible

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#59]
not sure if that's a viewer issue...
[link](https://bdrc-reader.github.io/mugey-gonpa/katan)
![image](https://user-images.githubusercontent.com/17675331/63522334-b5bef600-c52a-11e9-9faf-68046a9bfb15.png)

**Comment by eroux** [comment]
What's the issue?

**Comment by eroux** [comment]
ah ok I see, that's a problem in the data, not in the viewer
