### ISSUE TITLE
resizing issue going from embedded to full screen

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#60]
![gif](https://user-images.githubusercontent.com/17675331/63523647-164f3280-c52d-11e9-8ce8-5873a8c00106.gif)

directly in full screen:
![gif](https://user-images.githubusercontent.com/17675331/63523809-66c69000-c52d-11e9-90a9-471ad4b6afe2.gif)

**Comment by ngawangtrinley** [comment]
![gif](https://user-images.githubusercontent.com/17675331/65756249-42bb2780-e147-11e9-8cde-22d5ea30c0d6.gif)

**Comment by eroux** [comment]
@berger-n can you take a look?

**Comment by berger-n** [comment]
fixed as of https://github.com/buda-base/mirador/commit/bdcea44e2ad2228b8f33c05e814606ee8bfe8089
