### ISSUE TITLE
replace "items" by "pages"

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/buda-iiif-presentation#64]
![image](https://user-images.githubusercontent.com/17675331/63842807-e7ffa600-c9b7-11e9-85ce-1ec1c6553288.png)

**Comment by eroux** [comment]
I agree that "items" is an unnecessarily generic term... but "pages" could be a bit confusing, maybe "images"?

**Comment by ngawangtrinley** [comment]
agreed!
