### ISSUE TITLE
problem with work in volume manifest

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-presentation#66]
[bdr:W22334_0054](http://purl.bdrc.io/resource/W22334_0054.ttl) has a location information but

https://iiifpres.bdrc.io/wvo:bdr:W22334_0054::bdr:V22334_I3867/manifest

displays the whole volume... (note that the `wv:` version doesn't have this problem)

**Comment by eroux** [comment]
@tadhondup can you give it a try?

**Comment by tadhondup** [comment]
I am on way to home now. I will try

**Comment by tadhondup** [comment]
It works for some collections but few is still not. Maybe its catalogues
problem.

**Comment by eroux** [comment]
can you give me an example of a collection that doesn't work please?

**Comment by tadhondup** [comment]
I put it on the issue buda-iiif-preservation on github.
