### ISSUE TITLE
The collection, can not find Text from the collection

### ISSUE THREAD

**Issue by tadhondup** [buda-base/buda-iiif-presentation#67]
![12](https://user-images.githubusercontent.com/28945342/64534510-2a29cf80-d348-11e9-89b5-abbcb70b71a9.gif)

**Comment by eroux** [comment]
thanks! can you try with your browser cache empty? I think that's the problem, this one should work

**Comment by tadhondup** [comment]
Yes you are right. it works after clean my bowser cache. But some texts from this collection exist in tbrc.org but can not display in new website. I tried it in New incognito too. Not sure about it,why.

**Comment by eroux** [comment]
ok thanks, I can't do anything without an example though, would you have one please?

**Comment by tadhondup** [comment]
Example 1
![12](https://user-images.githubusercontent.com/28945342/64538666-9bb94c00-d34f-11e9-971c-858eadb3b20b.gif)

**Comment by tadhondup** [comment]
Example 2
![13](https://user-images.githubusercontent.com/28945342/64538759-c3a8af80-d34f-11e9-9c4b-4867e6bcfa41.gif)

**Comment by eroux** [comment]
Thanks, just the work numbers would be enough though, it's a bit long to sit through the whole video to get them! In any case, this is a different problems, see https://github.com/buda-base/buda-iiif-server/issues/44

**Comment by eroux** [comment]
note that this problem shouldn't affect the embedded viewer though, it's jut a problem on the library (seehttps://github.com/buda-base/public-digital-library/issues/93 ), for instance http://library.bdrc.io/view/bdr:W22334_0052 works fine
