### ISSUE TITLE
Text nodes and custom pages not working on buda & embedded readers

### ISSUE THREAD

**Issue by tadhondup** [buda-base/buda-iiif-presentation#70]
This issue is true for all works. For instance [W23702_3915](http://library.bdrc.io/show/bdr:W23702_3915) displays image [0003.tif](https://iiif.bdrc.io/bdr:V23702_I1PD31519::I1PD315190003.tif/full/max/0/default.png) while it should be [0307.tif](https://iiif.bdrc.io/bdr:V23702_I1PD31519::I1PD315190307.tif/full/max/0/default.png), the first image of the text...

![image](https://user-images.githubusercontent.com/17675331/65667057-86dbf880-e071-11e9-99f1-62e3f90fee5b.png)

Another instance [here](http://library.bdrc.io/show/bdr:W22273_0522)

**Comment by eroux** [comment]
it should be working again, can you test (with your browser cache off)?

**Comment by tadhondup** [comment]
Thank you. Its waorking now.

**Comment by tadhondup** [comment]
![image](https://user-images.githubusercontent.com/28945342/65758139-1d301d00-e14b-11e9-82e4-73a947712270.png)
[Embedded reader link](https://github.com/buda-base/embedded-reader-import/blob/master/input/W1ERI0018.tsv#L6)

**Comment by eroux** [comment]
yes, see https://github.com/buda-base/embedded-reader-import/issues/7
