### ISSUE TITLE
negative index in ManifestService

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/buda-iiif-presentation#82]
https://iiifpres.bdrc.io/wvo:bdr:W1PD8_0020::bdr:V1PD8_I1PD84/manifest fails.

I traced it to the point where the index imageSeqNum is zéro and leads to a negative index for the image list. It happens here:

https://github.com/buda-base/buda-iiif-presentation/blob/master/src/main/java/io/bdrc/iiif/presentation/ManifestService.java#L115

**Comment by eroux** [comment]
thanks! fixed
