### ISSUE TITLE
missing CORS header in the PUT function

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-presentation#85]
For the `/bvm/{something}`, the CORS headers should allow the `PUT` method to be called, currently it's not (only `GET`, `HEAD` and `OPTIONS` are). It would be best to have the CORS headers have `PUT` just for that endpoint, but if in a first time we have it for all it shouldn't be a problem

**Comment by MarcAgate** [comment]
Fixed as of commit 20bffcd
