### ISSUE TITLE
can't open page in image view 

### ISSUE THREAD

**Issue by berger-n** [buda-base/buda-iiif-presentation#96]
here: https://library.bdrc.io/view/bdr:I01CT0073
if you click on an image then nothing is shown:

![image](https://user-images.githubusercontent.com/33383857/90263748-6024dd00-de50-11ea-9b33-81d12bf1a365.png)

this might has to do with corresponding [info.json](https://iiif.bdrc.io/bdr:I01CT0074::I01CT00740001.tiff/info.json)
which either returns a 500 or an empty/buggy json file:

![image](https://user-images.githubusercontent.com/33383857/90263942-a67a3c00-de50-11ea-9fe1-8881a9d97a00.png)

**Comment by eroux** [comment]
the issues in the `/info.json` URLs should be reported to https://github.com/buda-base/buda-iiif-server
